### ISSUE TITLE
Cannot read property 'animate' of undefined

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [kimmobrunfeldt/progressbar.js#100]
Hello ProgressBar team,

On the index page we have a function in a src js file with a few progressLine.animate(); calls that progress in value.
On the index page we call this function because we want to run this function on the background but we don't want to show a progressbar.
We only want to show the progressbar on a certain page when we call this function manually.
We have defined the var progressLine globally but we keep on ending up with: Cannot read property 'animate' of undefined

Can you advise how we can keep progressLine.animate() included in a code snippet but without getting the error message?

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
What I ended up with is make sure the "progressbar.min.js" is loaded before the script is called.
And create a dummy container like: var progressLine= new ProgressBar.Line('#dummyProgressBar');

If there is another way please advise.

Kind regards,
Mario

**Comment by kimmobrunfeldt** [comment]
The error means that ProgressBar.js library is not correctly loaded at the point of code where you call `.animate` method. 

You can follow these steps to get progressbar.js loaded to your web app: http://progressbarjs.readthedocs.org/en/latest/#get-started

This is not an issue with ProgressBar.js.
