### ISSUE TITLE
Resizing Text in Circle  

### ISSUE THREAD

**Issue by AndaniB** [kimmobrunfeldt/progressbar.js#103]
Hi, 

I see PR has adopted the HTML API.
I am however unable to change font sizes.
	text: {
							value: '0%',
							
							style:{
							
								 color: '#7F6F82',
								 position: 'absolute',
								left: '50%',
								top: '50%',
								padding: 0,
								margin: 0,
								font-size:16
								
									}
							
							},

**Comment by kimmobrunfeldt** [comment]
This works:
```
var circle = new ProgressBar.Circle('#container', {
    color: '#FCB03C',
    text: {
      value: 'test',
    	style: {
        // or fontSize: '28px'
        'font-size': '28px'
      }
    }
});

circle.animate(1.0);  // Number from 0.0 to 1.0
```

The HTML API is not ready yet. Only text is supported for now.
