### ISSUE TITLE
Way to pause on event?

### ISSUE THREAD

**Issue by Lanteal** [kimmobrunfeldt/progressbar.js#105]
Is there a way, to pause the animation on event, e.g. on mouseover? Didn't figure if it is possible.

Thx for that great tool!

**Comment by kimmobrunfeldt** [comment]
You can stop animation with `.stop()` method. See the API doc: https://github.com/kimmobrunfeldt/progressbar.js#shapestop

You need to manually do the event handler for mouseover which calls .stop() method.

**Comment by brucemcpherson** [comment]
Thanks also for this great tool. More on this question though.. how do you pause, then restart exactly as you were. .stop() stops it fine, but if then use .set (bar.value()) and .animation(1) , then the complete line resets to starting color. I'm trying to understand how to make something as simple as bar.pause() and bar.resume()

thank you for any tips on how to achieve.

**Comment by kimmobrunfeldt** [comment]
The api doesn't support this. Shifty supports the feature but prgressbar isn't using it. Would be quite straightforward to implement. I would accept a PR for this.

**Comment by brucemcpherson** [comment]
thank you. I'll have a look at it.

cheers
bruce

**Comment by ciustuc** [comment]
+1 to this, would love to use .pause() .resume()
