### ISSUE TITLE
animation anti-clockwise

### ISSUE THREAD

**Issue by lewisjwright** [kimmobrunfeldt/progressbar.js#110]
Not so much an issue than a question really:

Is there a way to animate the circle to go anti-clockwise instead of clockwise? 

For readers benefit:

The reason I ask this question is because a client wants to show negative values on the circle and would like them to animate anti-clockwise.

Any help would be greatly appreciated!

Thanks,

**Comment by denkomanceski** [comment]
I would also like to make a timer, which will start from 10 and lower to 0 - > anti-clockwise, but cant seem to find a way to do it

**Comment by denkomanceski** [comment]
I found how to do it:
You should make `circle.set(1);` before 
` circle.animate(0, function() {
            circle.animate(0);
        })`

**Comment by kimmobrunfeldt** [comment]
You could maybe achieve this with some CSS transformations but it is not supported by this library. Other option would be to draw the path counter clockwise in circle.js.

**Comment by lewisjwright** [comment]
Thanks for the suggestions guys! I will close the thread since there are suggestions that should definitely work. :)
