### ISSUE TITLE
New demo page

### ISSUE THREAD

**Issue by kimmobrunfeldt** [kimmobrunfeldt/progressbar.js#111]
Working with this in new-demo-page branch.

**TODO:**

* [x] Initial page style design
* [x] Intro text
* [x] Slideout menu https://github.com/Mango/slideout for mobile support
* [x] Intro demo
* [x] Line demos
* [x] Circle demos
* [x] SemiCircle demos
* [x] Custom demos

**Comment by Inlesco** [comment]
Good to hear. This is a great lib! :)

**Comment by kimmobrunfeldt** [comment]
The new demo page is now public
