### ISSUE TITLE
How can I change the min and max value in a progressbar?

### ISSUE THREAD

**Issue by joomlastars** [kimmobrunfeldt/progressbar.js#112]
Hi,

In the template sample data all the progress bars uses by default the 0 to 100 range.

How can I change the min and max value in a progressbar?
we want to set the min value to start the progressbar animate from
For example: start animate from 20 to 90
Not from 0 to 90
Thanks :)

**Comment by kimmobrunfeldt** [comment]
Hi,

Progressbar uses 0.0 - 1.0 floating values for the progress value. You have to fit your new range to the 0.0-1.0 range, which is simple math operation.

**Comment by kimmobrunfeldt** [comment]
Did this answer your question?

**Comment by joomlastars** [comment]
Hi,

No

there is value from 0 to 100

i want to change that min and max value


*Thanks,*


<http://www.joomlastars.co.in/>


*Joomlastars *


Website: http://www.joomlastars.co.in/ <http://joomlastars.in/>

Phone: +919033712682

skype: stars.joomla


Facebook <https://www.facebook.com/joomlastars> | Twitter
<https://www.twitter.com/joomlastars> | Themeforest
<http://themeforest.net/user/joomlastars/portfolio?ref=joomlastars>

**Comment by kimmobrunfeldt** [comment]
Sorry but I don't understand what you are requesting for. Could you draw what you mean?

**Comment by kimmobrunfeldt** [comment]
Closed because of inactivity.
