### ISSUE TITLE
stroke-dashoffset issue

### ISSUE THREAD

**Issue by jconnor34** [kimmobrunfeldt/progressbar.js#113]
I am using the circle progress in Firefox 44.02 and Chrome 43.0.2357.134 (64-bit).  I am getting the circle progress constantly changing.  I checked the Inspector and it is showing the stroke-dashoffset constantly changing.  Do you know why this might be happening?

My container is "#container1" and is 300x300 px.

I instantiate with:

`this.circle = new ProgressBar.Circle("#container1",
				{
					color:#333,
					strokeWidth:10,
					fill:rgba(0,0,0,0),
					duration:250,
					easing: "easeInOut",
					trailColor:#aaa
				});`

I then use the following to change the value:
`this.circle.animate(0.5);`

**Comment by jconnor34** [comment]
I tracked down what seems to be the cause of the issue and it is when I set the option

duration:250,

When I remove the duration option everything works fine.

**Comment by kimmobrunfeldt** [comment]
The constant changing of stroke-dashoffset is normal. Animating that property is how the whole library works. See http://progressbarjs.readthedocs.org/en/latest/#how-it-works

Is this there another problem besides that?

**Comment by jconnor34** [comment]
It keeps animating even when not calling animate.  It should animate until it reaches the target value.   What I am seeing is that it reaches the target and keeps going around in circles and never stops.  
As I posted in my last post, I found that when I don't specify duration it works correctly.   If I use duration of
Duration : 250
It does the odd behavior.

**Comment by kimmobrunfeldt** [comment]
Which browser are you using? I can't reproduce this issue in Chrome or Firefox with this code: http://jsfiddle.net/kimmobrunfeldt/L2ka5c0h/

```js
var circle = new ProgressBar.Circle('#container', {
    strokeWidth: 10,
    duration: 250,
    easing: 'easeInOut',
    trailColor: '#aaa',
    color: '#FCB03C'
});

circle.animate(0.5);  // Number from 0.0 to 1.0
```

**Comment by jconnor34** [comment]
Ok, I think I found what I was doing wrong.  Thanks for the jsfiddle.  I was doing 
Duration:"250"
Using a string instead of an integer causes the issue.  I was passing in the options in with Json and I had the duration set as a string.
Thanks for your help Kimmo!

**Comment by kimmobrunfeldt** [comment]
Ok great. No problem :+1:
