### ISSUE TITLE
Fire on hover?

### ISSUE THREAD

**Issue by dantahoua** [kimmobrunfeldt/progressbar.js#116]
Hello.
Is it possible to fire the animation when hovering a div? I tired this but it's not working:
`
$('document').ready(function() {
    var path1 = new ProgressBar.Path(document.getElementById('circle1'), {
        duration: 1000,
        easing: 'easeOut'
    });
    $('#svglink-1').hover(function() {
        path1.animate(1);
        path1.animate(0);
    });
});`
and the html:
`<a id="svglink-1" class="">
        <div class="big-box nature">
                <div class="svg-button centered-axis-xy">
                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                         viewBox="0 0 224.10257 224.10257">
                        <path fill-opacity="0" stroke-width="10" stroke="#fff" d="M5,112.05128C5,52.92849,52.92849,5,112.05128,5s107.05128,47.92849,107.05128,107.05128
	s-47.9285,107.05128-107.05128,107.05128"/>
                        <path id="circle1" class="toprogress" fill-opacity="0" stroke-width="10" stroke="#197dbe" d="M5,112.05128C5,52.92849,52.92849,5,112.05128,5s107.05128,47.92849,107.05128,107.05128
	s-47.9285,107.05128-107.05128,107.05128"/>
</svg>
                </div>
        </div>
    </a>`
It's not working. Note that if I use path1.animate(1) without the hover function, the animation shows when loading the page

**Comment by kimmobrunfeldt** [comment]
One problem is this: `path1.animate(1); path1.animate(0);` You cannot call animate(0) immediately after animate(1) like that. You need to do it via callbacks

```js
path1.animate(1, function() {
  path1.animate(0);
});
```

**Comment by dantahoua** [comment]
Oh yeah, I was tired yesterday, in fact with the "hover" jquery function, the right spelling is:
`$('#svglink-1').hover(function() {path1.animate(1);},function() {path1.animate(0);});`
Now it's working great! :)
