### ISSUE TITLE
Percent value for stroke width on circular progress bar

### ISSUE THREAD

**Issue by ethanclevenger91** [kimmobrunfeldt/progressbar.js#117]
I'm using the circle mode and my progress bars will appear in a variety of settings of varying widths. Having the stroke width set relative to the width of the container helps things scale nicely. I noticed I can set `trailWidth` to a percentage, but not `strokeWidth`, as this causes a calculation issue when determining the path.

The workaround is to set it in CSS with an `!important`, but the value I pass to the JS still affects the size of the circle within its container, so it'd be nice to have that calculation consider the percentage.

Sound like something that could be added in the future? I could also look into placing a PR myself.

Cheers!

**Comment by ethanclevenger91** [comment]
Working on a PR - how do I set up Karma env variables?

**Comment by kimmobrunfeldt** [comment]
You don't need to run the sauce labs tests, you can use npm test which will use testem to run tests. It shouldn't need env vars.

**Comment by Dave-Hughes** [comment]
@ethanclevenger91 What is the CSS selector for the strokeWidth? I can't seem to figure out how to target it.
