### ISSUE TITLE
not defined error 

### ISSUE THREAD

**Issue by nickbijmoer** [kimmobrunfeldt/progressbar.js#118]
Hello I got a Uncaught ReferenceError: circle is not defined error, I use this code:

window.onload = function onLoad() {
	var circle = new ProgressBar.Circle('#items-canvas', {
		color: '#33cc33',
		duration: 1500,
		trailWidth: 1,
		strokeWidth: 5,
		easing: 'bounce'
	});
        if(!timerRunning){
            circle.animate(1);
        }
}

anybody knows a fix?

**Comment by kimmobrunfeldt** [comment]
Clean up your code indentation please. You have some basic reference error there.
