### ISSUE TITLE
is it possible to change the direction of a circular progress bar 

### ISSUE THREAD

**Issue by balasivagnanam** [kimmobrunfeldt/progressbar.js#120]
Thanks for this nice library.

is it possible to change the direction of fill from clockwise to anti-clockwise?

**Comment by kimmobrunfeldt** [comment]
Not sith the bultIn shapes. You can do a custom shape where the path goes counter-clockwise. I might add this option to built in shapes since this has been requested a few times.

**Comment by balasivagnanam** [comment]
any tips on where i should look to do this? I am new to shapes, path and svg. Thanks

**Comment by marcelo-ribeiro** [comment]
I want to do the same. Any tips on where i should look to do this?

**Comment by yoplaboom** [comment]
Hi, there is an easy workaround. Just set a negative animate value :)

**Comment by kimmobrunfeldt** [comment]
It indeed seems that using negative values from  -1.0 to 0 does the trick. This wasn't designed in the library and I'm not sure how different SVG rendering engines in browsers handle that. But e.g. if you want to animate 70% anti-clockwise, use `.animate(-0.7)`.

Closing this for now. If someone encounters problems with that approach, please reopen.
