### ISSUE TITLE
Multiple bars from class instead of ID?

### ISSUE THREAD

**Issue by jesperlandberg** [kimmobrunfeldt/progressbar.js#126]
Hi,

Is it possible to animate multiple bars at the same time? If five bars have the class "progress" for example?

**Comment by kimmobrunfeldt** [comment]
Yes you can animate multiple instances of progress bars. You need to have direct JS references to the ProgressBar instances to animate them.

E.g. not tested ES6 code:
```js
var bars = ['#line1', '#line2'].map(id => new ProgressBar.Line(id));
bars.forEach(bar => bar.animate(1);
```
