### ISSUE TITLE
Dynamic sized containers

### ISSUE THREAD

**Issue by emwardell** [kimmobrunfeldt/progressbar.js#127]
I'm using bootstrap columns to display three circle progress bars next to each other. It works very well when resizing the window and keeps everything the right size. However, with a recent upgrade of progressbar.js I now see the "Incorrect aspect ratio of container" warning in the console. Putting a height and width on the container element class removes the warning but kills the responsive dynamic nature of bootstrap columns that works great. Any ideas how to either disable the warning or integrate bootstrap with progressbar.js?

**Comment by kimmobrunfeldt** [comment]
The warning seems to be a bit unnecessary.. I could take it away.

**Comment by emwardell** [comment]
Ok I will just ignore the warnings for now then. Thanks

**Comment by kimmobrunfeldt** [comment]
This warning is now disabled in 1.0.1 version.
