### ISSUE TITLE
Restart animation

### ISSUE THREAD

**Issue by marcelo-ribeiro** [kimmobrunfeldt/progressbar.js#129]
How to restart the animation after the end of time?

**Comment by kimmobrunfeldt** [comment]
You'll need to use the animate callback for restarting:

```js
var bar = new ProgressBar.Line('#a', { /* opts */ });

// Animate to 100% and back to 0%
function loop(cb) {
  bar.animate(1, function() {
    bar.animate(0, cb);
  }); 
}

// Loop the animation forever
setInterval(function() {
  loop(function() {
    bar.set(0);  // set immediately to 0% without animation
  });
}, 5000);
```

**Comment by kimmobrunfeldt** [comment]
See API docs for more: http://progressbarjs.readthedocs.org/en/latest/api/shape/

**Comment by AdrienChauvet** [comment]
In this case, using a SVG path, the function setInterval prevents the animation to start for a duration equal to its second parameter. How do you avoid this behavior?
Thank you for your help.

`window.onload = function onLoad() {
					var bar = new ProgressBar.Path('#filling-bar', {
						duration: 8000,
						easing: 'linear'
					});

					// Animate to 100% and back to 0%
					function loop(cb) {
					  bar.animate(1, function() {
					    bar.animate(0);
					  }); 
					}

					// Loop the animation forever (prblème : marche bien mais démarre après 16 secondes...)
					setInterval(loop, 16000);
			};`

**Comment by dixiekun** [comment]
how to add the loop animation callback for 4 different circles?
thanks!

**Comment by dixiekun** [comment]
how to use animate callback on multiple progress bars?  
thank you.
