### ISSUE TITLE
Unnecessary container size warning 

### ISSUE THREAD

**Issue by yoplaboom** [kimmobrunfeldt/progressbar.js#130]
Hi, i'm using GWT and when i create the progressbar i give the container element but this element is not yet attached to the DOM. So i have a warning in console `Incorrect aspect ratio of container ....​ (width) / (height) = NaN`.
It's not really a problem but it show a useless warning in my console (for this case).

**Comment by kimmobrunfeldt** [comment]
Let's continue this issue here https://github.com/kimmobrunfeldt/progressbar.js/issues/127
