### ISSUE TITLE
Wider strokePath for smaller circles

### ISSUE THREAD

**Issue by Dave-Hughes** [kimmobrunfeldt/progressbar.js#131]
I've been playing with the examples in JSFiddle for a while now and I can't find a good balance between making the circle smaller and keeping a thicker/wider strokePath.

Is there a way to manually override the stroke path in CSS or some options I haven't found in the official docs? I'm trying to use circles that are around 45px width and height, but the stoke path becomes extremely narrow at that size.

**Comment by kimmobrunfeldt** [comment]
The stoke width is always a percent value relative to the size of svg canvas element. You can find more from svg specification.

Did you already try the strokeWidth option for progressbar? Some svg properties are possible to edit with css but I'm not sure if stroke-width is one of them.

**Comment by Dave-Hughes** [comment]
Apparently there is a [stroke-width css property](https://css-tricks.com/almanac/properties/s/stroke-width/), but I didn't have much luck getting it to update the width of the ProgressBar strokes, maybe because the script is loaded in after and overrides any CSS value? Not sure.

Either way, I believe the problem I was having is when using the ProgressBar.Circle text property. If I don't use it, then I'm able to have a small circle with a wide stroke and it works great, but if I add the text property back in, it seems to really throw off the scaling.

I can always just use my own text options though.

Thanks for the response!

**Comment by kimmobrunfeldt** [comment]
The text option shouldn't affect the strokeWidth in any way.


This works fine for me:

```js
var circle = new ProgressBar.Circle('#container', {
    color: '#FCB03C',
    strokeWidth: 10,
    text: {
      value: 'test'
    }
});
```

<img width="46" alt="screenshot 2016-05-03 23 04 31" src="https://cloud.githubusercontent.com/assets/1232405/14996601/6bf74756-1183-11e6-82f2-01757f5a1045.png">


You can also modify the value with CSS like this, where `#container` is the container which you use when initializing ProgressBar instance.
```css
#container > svg > path:last-child {
  stroke-width: 2;
}
```

**Comment by kimmobrunfeldt** [comment]
You can read more about the HTML structure ProgressBar.js is generating in here: http://progressbarjs.readthedocs.io/en/latest/api/general/#html-structure

You can consider this DOM structure quite safe to be relied on. I'll bump the major version if the generated DOM structure will change.

**Comment by Dave-Hughes** [comment]
Thanks! Very helpful. Not sure how I missed that in the docs.

**Comment by Dave-Hughes** [comment]
To make use of the "text" option, do I only need to add:
`text: {
      value: 'test'
    }`

If your above example it seems that is the case, but when I only add that, I have no change to my circles.

I used this from the docs:
`
var circle = new ProgressBar.Circle('#example-percent-container', {
    color: '#FCB03C',
    strokeWidth: 3,
    trailWidth: 1,
    text: {
        value: '0'
    }
});
`

But I don't even get the <p> tag in my DOM when I inspect the circle.
