### ISSUE TITLE
Change bar color via javascript?

### ISSUE THREAD

**Issue by mamarilmanson** [kimmobrunfeldt/progressbar.js#133]
Would be possible to change color of the bar by logic? I'm trying to use it in a grading system... if passed [this color] and if failed [another color]? :)

**Comment by kimmobrunfeldt** [comment]
Yeah it's possible by setting stroke attribute for `.path`. See this example: https://jsfiddle.net/kimmobrunfeldt/swc64gg3/

**Comment by mamarilmanson** [comment]
Thanks... :D
