### ISSUE TITLE
For Angular2/Ionic2

### ISSUE THREAD

**Issue by mamarilmanson** [kimmobrunfeldt/progressbar.js#134]
Is there a (very) basic implementation of progress bar for Ionic2(maybe closest to Angular2)??? used this before in Ionic1 but it seems to be more difficult to implement in Ionic2 while using Angular2... :)

**Comment by kimmobrunfeldt** [comment]
I haven't used Angular so can't point you to any example. React is very different but here's an example how progressbar.js can be integrated to React https://github.com/kimmobrunfeldt/react-progressbar.js/blob/master/src/main.js

**Comment by ksachdeva** [comment]
Here it is
https://github.com/ksachdeva/angular2-progressbar
https://github.com/ksachdeva/angular2-progressbar-example

Regards
Kapil

**Comment by wrosb** [comment]
Hey! I found this: https://github.com/ksachdeva/angular2-progressbar.

Not tested yet but i will do it next days.
