### ISSUE TITLE
positive/negative bar

### ISSUE THREAD

**Issue by Kyamu56121** [kimmobrunfeldt/progressbar.js#135]
@kimmobrunfeldt I have a sort of oddball issue.
I am trying to create a progress bar that starts in the center of a bar, and moves either left (up to -100) or right (up to +100). The standard line will start on the right and move left if a negative value is given when it is animated.

Do you have any suggestions for how I might go about this?

**Comment by kimmobrunfeldt** [comment]
Interesting question. Right now the only possible solutions I can come up with would be to use two Line progressbars.

I tried to test if you could do it like this:

```
1. Draw line right (L command)
              ----------->

2. Move back to start  (M command)
|             ----------->

3. Draw line to center (L command)
----------->---------->

4. Finished path
---------->----------->
 -0.5 - 0    0 - 0.5
```

But it didn't work. Check this JSfiddle https://jsfiddle.net/7rsdpc59/1/

**Comment by kimmobrunfeldt** [comment]
I actually got it working! I just had to keep the path as a continuous line.

Now the line is formed like this:

```
1. Draw line right (L command)
             ------------>

2. Draw line to start  (L command)
<-------------------------

3. Draw line to center (L command)
------------>

4. Finished path
<----------->------------>
 -0.25 - 0    0 - 0.25
```

Now you can animate between -0.25 and 0.25 to achieve the effect.

**Comment by kimmobrunfeldt** [comment]
Closing the issue, solution above.

**Comment by axstavo08** [comment]
Hello guys,

I develop an example for this case.

It could be an alternative for this purpose and show negative values using two progressing bars.

I want to share my solution with us. [Js Fiddle](https://jsfiddle.net/rfny4ftb/2828/)

Regards.
