### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by mitrich38** [kimmobrunfeldt/progressbar.js#136]
Hello @kimmobrunfeldt! Thanks a lot for you progressbar.js! It's great work!
Your demo page work on Safari browser but if i open example  code on jsfiddle.net ( for example https://jsfiddle.net/kimmobrunfeldt/k5v2d0rr/ ) it doesn't  work on Safari browser.
Could you fix it, please!

**Comment by iNilo** [comment]
Why is this closed?

https://jsfiddle.net/kimmobrunfeldt/sqwdkrg0/

Doesn't show up in Safari (iOS 8.4)
