### ISSUE TITLE
Wrong position

### ISSUE THREAD

**Issue by sodbileg** [kimmobrunfeldt/progressbar.js#140]
I'm having an issue with the bar position. For example, on [this](https://jsfiddle.net/kimmobrunfeldt/rfny4ftb/) example, you can see the bar is on below the position it should be on and it makes some issues with the site design. Should there be any CSS reset or something like that? Or is it the default behavior?

![screenshot 2016-07-03 21 48 42](https://cloud.githubusercontent.com/assets/1418797/16545517/4e470eca-4168-11e6-8306-2c559d729682.png)

**Comment by kimmobrunfeldt** [comment]
Weird, I haven't noticed this before. I don't know what exactly causes this but it shouldn't be in the incorrect position. Seems like a bug to me.

**Comment by sergiu-radu** [comment]
@sodbileg add `display: block` to svg, [example](https://jsfiddle.net/yuaqs7fa/) here.

**Comment by sodbileg** [comment]
@sergiu-radu Yes, that's it. Thanks.
