### ISSUE TITLE
Starting animation at point later than 0

### ISSUE THREAD

**Issue by ldk7zf** [kimmobrunfeldt/progressbar.js#141]
I am trying to make a circle animation that updates when the value changes, I am passing in the value to a function that draws the circle. 

After the initial loading of the page my drawCircles function is called only when the number being passed in as the value is updated. When this happens, instead of starting the animation from 0 again I want to start from the previous value to the new value. 

Has anyone come up with a way to do this with a combination of set() and animate() or any other functions?

**Comment by kimmobrunfeldt** [comment]
I'm not sure if I understand what you mean. Calling `.animate()` always animates the bar starting from the position where it currently is. See this example: https://jsfiddle.net/kimmobrunfeldt/1wep1uwp/

If you have a very fast stream of values and you would like to call `.animate()` repeatedly, the animation unfortunately doesn't behave optimally. Calling `.animate()` always stops the previously running animation. Is this your use case?

**Comment by stramel** [comment]
@kimmobrunfeldt I believe @ldk7zf was looking to shift the origin around the circle. So many instead of 0 being the top it is the bottom.

**Comment by kimmobrunfeldt** [comment]
@stramel Thanks for the solution. That would be the way to go :+1:
