### ISSUE TITLE
Semicircle with text - Doesn't show up in iOS Safari (8.4)

### ISSUE THREAD

**Issue by iNilo** [kimmobrunfeldt/progressbar.js#142]
There is no progress bar showing up 

Fiddle to try -> https://jsfiddle.net/kimmobrunfeldt/sqwdkrg0/

Thanks

**Comment by amirzandi** [comment]
Same problem here, Please resolve this as soon as possible.

**Comment by kimmobrunfeldt** [comment]
Could you specify which browser you are using? I'm seeing it fine with Chrome and Firefox

**Comment by NullableMe** [comment]
I have the same problem but with the line bar as well. The device I tested it on was an iPhone 6s running iOS 9.3.5. Browsers: Safari and Chrome (52.0.2743.84).

I managed to track down the problem to the step function. When I used the code below all the JavaScript on the paged stopped working.

`step: (state, bar) =>
{
bar.path.setAttribute('stroke', state.color);
}`

But if you use the code below it works like a charm.

`step: function(state, bar, attachment) 
{
bar.path.setAttribute('stroke', state.color);
}`

My money is on the lambda/arrow function. But maybe I’m just missing something obvious about this. If so, please ignore me. 

Anyhow, thanks for an awesome library.

**Comment by kimmobrunfeldt** [comment]
This is actually the same error as reported here: https://github.com/kimmobrunfeldt/progressbar.js/issues/146
