### ISSUE TITLE
Add Min and Max value to limit the range

### ISSUE THREAD

**Issue by masoudhaghi** [kimmobrunfeldt/progressbar.js#143]
Hi there,

First of all I like to thank you for the awesome code to make pretty cool progress bars.

I would like to request you to add a minimum and maximum values so we can adjust the limits of the progress bars. It's obvious that most of progress bars starts from 0 and progress to 100, but with adding an option to set the limits, it also can be used as gauges and chart controls to measure the values.

Regards

**Comment by kimmobrunfeldt** [comment]
How would you use the min / max limits? You can easily create your own API which e.g. supports values between 1-5 and you would linearly scale that range of numbers to the 0.0 - 1.0 that progressbar accepts.

As an example you would have to scale your own decided min / max range to the 0.0 - 1.0 value range:
```
1      2      3      4      5
0.0  0.2  0.4  0.6  0.8   1.0
```

**Comment by masoudhaghi** [comment]
@kimmobrunfeldt how would you use the scaling when your mini value is -25 and your max value is 10?
I understand your point, but while you have negative values and you wish to use the indicator to show your values, it's a little hard to use scaling as it use the scaled value and not the real value and cause confusion for the users.

**Comment by lutchit** [comment]
Hello, some news about this feature ?

**Comment by kimmobrunfeldt** [comment]
Thanks for the interest. However this is something I won't implement to progressbar. It's trivial to make the scaling function before calling progressbar API.

See e.g. https://stackoverflow.com/questions/13137348/scaling-range-of-values-with-negative-numbers?noredirect=1&lq=1 for scaling math.
