### ISSUE TITLE
How to addd a gradient as a color in a ProgressBar.Line?

### ISSUE THREAD

**Issue by eBaeza** [kimmobrunfeldt/progressbar.js#145]

**Comment by kimmobrunfeldt** [comment]
It is not possible with this library. See https://github.com/kimmobrunfeldt/progressbar.js/issues/139.

You can smoothly transition the color of the whole progress bar, but not the line as with a gradient color.

**Comment by eBaeza** [comment]
Hi! a few hours ago I finally resolved this.

``` js
let lineBar = document.querySelector('#line-progress')

let bar = new ProgressBar.Line(lineBar, {
  color: 'url(#gradient)', // pass the id of the lineGradient defined
  ...
})

// Define a linearGradient element 
// Notice that the "gradientUnits" attribute is set to "userSpaceOnUse" this is important to work properly
let linearGradient = `
  <defs>
    <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="0%" gradientUnits="userSpaceOnUse">
      <stop offset="20%" stop-color="tomato"/>
      <stop offset="50%" stop-color="purple"/>
    </linearGradient>
  </defs>
`

// append the lineGradient to svg
bar.svg.insertAdjacentHTML('afterbegin ', linearGradient);
```

**Comment by kimmobrunfeldt** [comment]
Oh cool! Thanks for sharing.

**Comment by waxxxd** [comment]
@eBaeza - Please update final line:

bar.svg.insertAdjacentHTML('afterBegin', linearGradient);

**Comment by eBaeza** [comment]
@waxxxd the following lines are no needed

```javascript
19   circle.path.setAttribute('stroke', state.color);
20   circle.path.setAttribute('stroke-width', state.width);
```

**Comment by nesard** [comment]
Another possible solution is to add the SVG in the HTML

<svg width="0" height="0">
      <defs>
        <linearGradient id="progress-gradient" gradientUnits="objectBoundingBox" x1="0" y1="0" x2="1" y2="2">
          <stop stop-color="#3ebf72"/>
          <stop offset="65%" stop-color="#23a7b9"/>
      </linearGradient>
      </defs>
    </svg>

The JS would look like this:

window.onload = function onLoad() {
	var circle = new ProgressBar.Circle('#gallons-indicator', {
		color: 'url(#progress-gradient)',
		duration: 3000,
		easing: 'easeInOut',
		strokeWidth: 4
	});

	circle.animate(1);

	var ctx = document.getElementById("canvas").getContext("2d");
    window.myLine = new Chart(ctx, config);
};
