### ISSUE TITLE
It is not showing up on either Mobiles or Tablets...Bad Problem

### ISSUE THREAD

**Issue by amirzandi** [kimmobrunfeldt/progressbar.js#146]
Thanks for creating such useful component, but it is not rendering on mobiles and tablets, doesn't matter what explorer you use. It is not showing up. 
Please resolve this bug as soon as possible! 

Regards,

**Comment by kimmobrunfeldt** [comment]
Could you specify what Mobiles or Tablets are not working? Also what browsers(and their versions) do they have? I have tested https://kimmobrunfeldt.github.io/progressbar.js/ with a few mobile devices including iPhone(Safari) and Android (Chrome) and the progressbars work.

**Comment by amirzandi** [comment]
Thanks for your response. 
please check this link: https://jsfiddle.net/kimmobrunfeldt/sqwdkrg0/ on your mobile or tablet.

I am opening the above link on my iPhone and also iPad through Safari as well as Google Chrome, nothing is showing up.

thanks.

**Comment by kimmobrunfeldt** [comment]
You are right it doesn't work. I have to debug it, but can't promise when.

**Comment by kimmobrunfeldt** [comment]
It was caused because the example was using arrow functions and I hadn't set JSFiddle to use Babel as the language. I fixed that example now. ProgressBar.js library code itself is working fine with mobile devices but this given demo was using ES6 features not supported in iPhone.
