### ISSUE TITLE
affichage progressbar

### ISSUE THREAD

**Issue by none61** [kimmobrunfeldt/progressbar.js#153]
Bonjour,
Excusez moi de vous déranger.
J'ai trouvé votre site contenant les diverses progressbar ainsi que le fichier progressera.js.

J'arrive à faire fonctionner comme sur votre site les diverses progressbar sur mon serveur apache.

Cependant lorsque je rentre une valeur a afficher, la barre commence toujours de zéro pour se charger jusqu'a la valeur souhaitée.

Auriez-vous une version qui affiche directement la valeur souhaité?

 Le but pour moi étant de les intergrer sur un "site" intranet qui me servirait a faire de la supervision (temperature, 0-10v etc ...)

Cordialement

Samuel Fromonot

**Comment by kimmobrunfeldt** [comment]
Thank you for contacting, but unfortunately I don't speak France. Google Translate helped a bit but I would need more context for helping.
