### ISSUE TITLE
Path animation finishing up sooner than expected

### ISSUE THREAD

**Issue by dionysio** [kimmobrunfeldt/progressbar.js#158]
Check out this jsfiddle:
https://jsfiddle.net/xduzs6tf/

The path fills up at 50%, not at 100% as I would expect. I have other paths that are simpler shapes and they work great but I cannot figure this one out. What am I doing wrong?

**Comment by kimmobrunfeldt** [comment]
It's hard to say directly why this happens because the shape is a bit complex, but could it be that the shape draws some of the lines double?

For this type of use case you might like these libs: https://connoratherton.com/walkway http://maxwellito.github.io/vivus/

**Comment by dionysio** [comment]
I am still not quite sure what caused it, but I do not think it was your plugin. 

Originally I made multiple objects, transformed them into paths and combined them. I have reworked that, so now it is just one long connected path and it works fine.

P.S. thanks for cool plugin :+1:
