### ISSUE TITLE
Infinite progressbar

### ISSUE THREAD

**Issue by luanfonceca** [kimmobrunfeldt/progressbar.js#160]
Hi folks, i want to do something like a infinite progressbar. like using a line with the `easeInOut` event and when it finishes it restart again and again.

Can someone help out on this?!

Thanks in advance.

**Comment by luanfonceca** [comment]
I handle it using this, at least it is working:

```js
var bar = new ProgressBar.Line($('.line')[0], options);
bar.animate(1);

setInterval(function() {
  bar.set(0);
  bar.animate(1);
}, 1000);
```

**Comment by kimmobrunfeldt** [comment]
That works too, or you could achieve this by recursively calling the animation function from the `.animate` method callback using a setTimeout.

**Comment by SachinBahukhandi** [comment]
Hi there I used this snippet but I am going through this error.Please help.

> Uncaught (in promise) 



Please help.
```    
    var circle = new ProgressBar.Circle("#loader", {
    color: "#555",
    trailColor: "#eee",
    strokeWidth: 10,
    duration: 2500,
    easing: "easeInOut"
    });
   circle.animate(1);

    setInterval(function() {
      circle.set(0);
      circle.animate(1);
    }, 1405);
```
