### ISSUE TITLE
Percentage text animate with Progress Bar

### ISSUE THREAD

**Issue by shuoor** [kimmobrunfeldt/progressbar.js#173]
How can i attach a percentage text with line progress bar so that icon will also animate with percentage.

Something like attached image

![ui progress](https://cloud.githubusercontent.com/assets/7921016/25079750/c6283a96-235c-11e7-99d1-25e4bfa4d383.jpg)

**Comment by kimmobrunfeldt** [comment]
Thanks for contacting. You can implement your own custom progress bas to achieve this. See example at https://jsfiddle.net/kimmobrunfeldt/dnLLgm5o/
