### ISSUE TITLE
Progress bar does not move properly on mobile when device is rotated. 

### ISSUE THREAD

**Issue by JDSlimz** [kimmobrunfeldt/progressbar.js#175]
I am developing a page that ises the progress bar. I have my layouts perfect with one exception. When i load the site in poitrait mode and rotate to landscape, my progress bar shifts from behind my play button and looks bad. The same thing happens when load in landscape and switch to poitrait. Is there a way to reinitialize the bar and have it reload css? Or could i bind it to the play button somehow? 

Site is currently at rar.jdslimz.ml for evidence of what I have said. Thanks bks.

**Comment by kimmobrunfeldt** [comment]
Could you provide a reproducable example of code? You can fork this JSFiddle: http://jsfiddle.net/kimmobrunfeldt/8xa87k31/392/.

**Comment by JDSlimz** [comment]
Unfortunately I cannot anymore. We deprecated that code because or product and subsequently our site have changed format and no longer need the progress bar. I think I managed to get it working back when we were using it but I don't have that code anymore. Sorry! Thanks for the great utility though!

**Comment by kimmobrunfeldt** [comment]
Ok thanks for the quick response. I'll close this issue for now.

**Comment by JDSlimz** [comment]
Ok, I have put together a new site that uses progressbar.js, it has a similar issue on mobile. https://vote.risingartistradio.com/ (user:test, pass:test) if you open it on desktop, its perfect, on mobile, its a little off.

html:
`<div id="progressbar"></div>`

css:
`#progressbar{
	height: 100%;
	width: 25vw;
	margin: 0 auto;
}`

js:
`var bar = new ProgressBar.Circle(progressbar, {
strokeWidth: 6,
easing: 'easeInOut',
duration: 0,
color: '#FFEA82',
trailColor: '#eee',
trailWidth: 1,
svgStyle: null
});`

`bar.setText('<i class="fa fa-play-circle" id="play" aria-hidden="true"></i>');
bar.text.style.color = 'blue';
bar.text.style.cursor = 'pointer';
bar.text.style.zIndex = '500';
bar.text.style.fontSize = '26vw';`

`jQuery('#play').click(function(){
jQuery('#play').toggleClass("fa-play-circle fa-pause-circle");`

`if(songPlaying){
song.pause();
} else {
song.play();
}
});`
