### ISSUE TITLE
Trigger animation when elements come into viewport

### ISSUE THREAD

**Issue by elenat82** [kimmobrunfeldt/progressbar.js#177]
Hi everyone,

the title says it all: when the page loads the animation runs but the elements are not visible until you scroll down to them.
How can I make the animation wait until the elements are in the viewport?

Thank you

**Comment by JulianHa** [comment]
I was asking myself the exact same thing. 
Have you found a solution yet? 

If I should find one I'll let you know.

**Comment by pebblerock** [comment]
@JulianHa @elenat82 

Perhaps this can help.

https://github.com/dirkgroenen/jQuery-viewport-checker

**Comment by elenat82** [comment]
Hi @JulianHa and @pebblerock ,

I tried using this library but with no success.  I set up a little demo in the attached zip.
Any help is really appreciated!

[prova.zip](https://github.com/kimmobrunfeldt/progressbar.js/files/998546/prova.zip)

**Comment by deadmanIsARabbit** [comment]
Hi,
try http://scrollmagic.io/. You can set an triggerelement, for example the SVG itself. 
This:
`
	line = new ProgressBar.Path('#id-of-the-svg-path', {
		easing: 'easeInOut',
		duration: 2400
	});
	line.set(0);
	secondLine = new ProgressB	
	var controller = new ScrollMagic.Controller();
	var desiredAnimation = new ScrollMagic.Scene({triggerElement: "#id-of-the-svg-path", duration: 200});
	desiredAnimation.addTo(controller);
	desiredAnimation.on("enter", function (e) {
		line.animate(1.0);
	});
`

**Comment by kimmobrunfeldt** [comment]
Thanks for contacting. Please use an external library for this feature as others have suggested.

**Comment by KostasRodolakis** [comment]
Try adding 

$(window).scroll();

at the end of your js
