### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by buzi** [kimmobrunfeldt/progressbar.js#179]
can the library support RTL direction ?
im trying to make the link draw from right to left..
Thanks

**Comment by kimmobrunfeldt** [comment]
I'm open for PR to RTL support. You could also achieve this by setting the inversing the outline and bar color and setting the value to 1.0 initially, then animate back to 0.0.

**Comment by buzi** [comment]
thank you

**Comment by sajjadab** [comment]
i have an solution for this 
you can add css style to svg and change its direction
below css code worked for me
.my div>svg{
-moz-transform: scale(-1, 1);
-webkit-transform: scale(-1, 1);
-o-transform: scale(-1, 1);
-ms-transform: scale(-1, 1);
transform: scale(-1, 1);
}
