### ISSUE TITLE
Set more than one text property

### ISSUE THREAD

**Issue by lourencogui** [kimmobrunfeldt/progressbar.js#181]
Hello guys, I'd like to know if you have implemented option to set more than one text property inside the graphic, not just the progress. I took a look in fiddle example and I noticed that setText function can only set one node text. I'd be grateful if you could help me.

Thanks.

**Comment by berserkore** [comment]
+1

**Comment by kimmobrunfeldt** [comment]
.setText should support any html nowadays, so you can add multiple text elements there.
