### ISSUE TITLE
progress number with decimal 

### ISSUE THREAD

**Issue by mangel1196** [kimmobrunfeldt/progressbar.js#184]
Hi, i have a question, i seek in the issues and not find something similar.

my question is: is possible to add a decimal in the progress number when it is progressing.

Thanks a lot.

Greets from Colombia

**Comment by dhruv-jain** [comment]
try this - var startColor = '#f66733';
var endColor = '#f66733';

$('.progress').each(function(i) {
    var circle = new ProgressBar.Circle(this, {
        color: startColor,
	    easing: 'easeInOut',
	    strokeWidth: 12,
        trailWidth: 15,
        trailColor: '#685C53',
	    duration: 3000,
	    text: {
	        value: '0'
	    }
	});
    
    var value = ($(this).attr('value') / 100);
    circle.text.style.fontSize = '1.35em';

	circle.animate(value, {
	    from: {
	        color: startColor
	    },
	    to: {
	        color: endColor
	    },
	    step: function(state, circle, bar) {
	        circle.path.setAttribute('stroke', state.color);
	        console.log(circle);
	        circle.setText((circle.value() * 100).toFixed(1)+'%'); //here you can specify decimal places, for example 1 in this case.
            
            
	    }
	});
});

**Comment by kimmobrunfeldt** [comment]
Yes you can override what the text shows by implementing a custom step function as @dhruv-jain demonstrated.
