### ISSUE TITLE
Progressbar doesn't work rendering circle graph initially

### ISSUE THREAD

**Issue by SangamBasnet** [kimmobrunfeldt/progressbar.js#186]
Hi,
Has there been any solutions to the issue we have been facing regarding graph rendering in IE and Edge. 
I found when it is first loaded on page it gives irregular graph and then when we comeback after visiting other pages it works fine. It is quite amazing to see such things. Have we got any solution to this on first visit of the page to be regular graph as wanted. 
I read like strokeWidth>7 works. But I found it is working fine when like i said above, besides, the problem is only when it is loaded at the first time when we visit the page.

**Comment by kimmobrunfeldt** [comment]
Unfortunately there hasn't been any solution to https://github.com/kimmobrunfeldt/progressbar.js/issues/79 that I know of yet.

Sorry, I didn't quite get the other parts of your issue description. I'm closing this issue, and let's continue the IE issue at #79.
