### ISSUE TITLE
Circle go countdown

### ISSUE THREAD

**Issue by bologer** [kimmobrunfeldt/progressbar.js#187]
Tried to read API and docs and did no find the following: 

Let's say I would like to make countdown instead. 

For example, on [this example](https://jsfiddle.net/72tkyn40/6971/), cound it going from 0 to 100. But I would to do the opposite way.

How to do it using native API of the plugin? If this does not exist, how to make it work for the moment? 

Also, maybe it will be useful for some people to have countdown for time period, let say between two dates. There are many of these already, but all of them are pretty raw and none of them are working properly.

**Comment by bologer** [comment]
Closed because of issue #164.

**Comment by bologer** [comment]
This still would be usefull: 
> Also, maybe it will be useful for some people to have countdown for time period, let say between two dates. There are many of these already, but all of them are pretty raw and none of them are working properly.

**Comment by kimmobrunfeldt** [comment]
The solution can be found in issue #164. For now, I'm not super excited to implement a new feature/progressbar if we can workaround this. All new code increases the size of this library. 

I'll close this due to inactivity and because I think this has been solved in the linked issue.
