### ISSUE TITLE
README formatting is borked

### ISSUE THREAD

**Issue by ds300** [kimmobrunfeldt/progressbar.js#190]
![image](https://user-images.githubusercontent.com/1242537/29124680-769547a8-7d11-11e7-87ee-d1b8b46fe5b2.png)

Looks like maybe github changed the way they render markdown with inline html — If I remove the `<br>` tags things look OK.

Same for react-progressbar and maybe others of your projects?

**Comment by kimmobrunfeldt** [comment]
Thanks for reporting :) This has been bothering me for a year now but haven't had a good moment to fix it. Fortunately there was a PR to fix it: https://github.com/kimmobrunfeldt/progressbar.js/pull/193

I was a bit surprised Github has released a breaking change for rendered, but on the other hand I was using an unofficial `<br>`  tag.
