### ISSUE TITLE
Is it possible to add a circular dot on the svg path head?

### ISSUE THREAD

**Issue by paritosharya007** [kimmobrunfeldt/progressbar.js#191]
I am trying to create the svg path with a progress bar with a large dot. How can I achieve it ?
![pmclg](https://user-images.githubusercontent.com/13437505/29163120-1da03b30-7dd9-11e7-835b-2a5d0c3f12e4.png)

Here's what I have so far: https://jsfiddle.net/fldeveloper/rLh2sr7u/

**Comment by kimmobrunfeldt** [comment]
This is an interesting issue for sure. I would try this:

Create a container with two divs inside it: 
 ```html
<div id="container">
  <div id="text-ball"></div>
  <div id="other-ball"></div>
</div>
```
and position the `div#text-ball` horizontally in center and to the correct offset from top. Then initialize `new ProgressBar.Circle('#container')` with a step function that will update the `div#other-ball` position using a bit of math. 

Here's a working example to put the pieces together: http://jsfiddle.net/tx3o0ut6/. You will still need to position the image correctly. See this issue for help: https://github.com/kimmobrunfeldt/progressbar.js/issues/64

Hope this helps!
