### ISSUE TITLE
Percentage doesn't support above 100%

### ISSUE THREAD

**Issue by sjoloughlin** [kimmobrunfeldt/progressbar.js#192]
I've been using the circular stats to display the percentage and recently came across a figure above 100% and unable to implement this.

I cannot find anything within the docs to allow for this inline. It would be good to have an additional attribute that accepts a text value.

Even if the bar animation stopped at 100%, but the text value continued to increase maybe.

Something like this:
`<div class="progress-circle" data-color="#5f6477" data-val="1" data-text="120"></div>`

**Comment by kimmobrunfeldt** [comment]
There isn't a really good support for values over the range of 0.0 - 1.0 but you can manually override the text by using e.g. `bar.setText('120%')`. 

Unfortunately inline attributes are not supported. Hope this helps.

**Comment by madiks** [comment]
found a way to support above 100%:

```javascript
var semi_circle = new ProgressBar.SemiCircle('#chart-container', {
        strokeWidth: 10,
        easing: 'easeInOut',
        color: '#439afa',
        text: {
            value: 'nodata',
        },
        trailColor: '#eee',
        trailWidth: 10,
        step: function(state, circle){
            var value = Math.round(circle.value() * 100)+'%';
            if (value === 0) {
                circle.setText('');
            } else {
                circle.setText(value);
            }
            // Notice, when circle.value() > 1 set trail to the same color as stroke
            if (circle.value() > 1) {
                circle.trail.setAttribute('stroke', '#439afa');
            }
        }
    }
);
semi_circle.animate(0.6);
setTimeout(function(){
    semi_circle.animate(1.6);
}, 3000);
```
when circle.value() > 1 set trail to the same color as stroke:

` circle.trail.setAttribute('stroke', '#439afa');`

**Comment by kimmobrunfeldt** [comment]
Closing as there seems to be a workaround.
