### ISSUE TITLE
Progress Path Animation Duration

### ISSUE THREAD

**Issue by TylerOlthuizen** [kimmobrunfeldt/progressbar.js#198]
Is it possible to have the animation load the same amount of time that the window is loading. In case someone has slow internet , the animation wont finish in 2 seconds and just be sitting there waiting until the page is done loading.

Does this make sense?

**Comment by kimmobrunfeldt** [comment]
I believe this is possible. However this isn't directly related to this library's functionality. You can search for methods of finding out the loading progress and feed that to progressbar.js
