### ISSUE TITLE
Ability to add % to circle progress bar multiple properties

### ISSUE THREAD

**Issue by benjam23** [kimmobrunfeldt/progressbar.js#199]
Hi, could you tell me the code to add text or a % to the progress bar multiple properties?

At the moment it only shows figures when a progress bar should show the percentage symbol alongside the number.

**Comment by Sawnan** [comment]
Help

**Comment by pavanjava** [comment]
Hi benjam

I did not get the question that you are intended, but this is what i have done to plot the progress bar with percentange of some calculation

 var progressbarVal = $scope.usageCalculation/($scope.selectedSubscription.dataLimit/1024);
                    var path = document.querySelector('#progressbar_container > svg > path:last-child');
                    bar.animate(progressbarVal);  // Number from 0.0 to 1.0
                    if(progressbarVal >= 0 && progressbarVal < 0.8){
                        path.setAttribute("stroke", "#7EB338");
                    }else if(progressbarVal >= 0.8 && progressbarVal <= 0.95){
                        path.setAttribute("stroke", "#FFC627");
                    }else {
                        path.setAttribute("stroke", "#EE3124");
                    }

**Comment by kimmobrunfeldt** [comment]
Unfortunately I didn't understand what's the issue here, sorry. Closing as unclear.
