### ISSUE TITLE
Full Circle with multiple purposes does not work in Chrome since version 61

### ISSUE THREAD

**Issue by radmedov** [kimmobrunfeldt/progressbar.js#200]
Full Circle with multiple properties does not work in Chrome since version 61.

In Chrome 60 it works perfectly.
What's the cause of such behavior?
There is my code: https://radmedov.github.io/

**Comment by kimmobrunfeldt** [comment]
Thanks for reporting. I can't say what's wrong by looking at the site. Could you please isolate the issue to a JSFiddle: http://jsfiddle.net/kimmobrunfeldt/8xa87k31/392/ and open a new issue for that?
