### ISSUE TITLE
Multiple same name class select and give the same auto progress

### ISSUE THREAD

**Issue by MdAshfaqurRahman** [kimmobrunfeldt/progressbar.js#203]
Please see me the code on tee following link.
Problem is not to perform 2nd or more same class name at the same auto progress
https://jsfiddle.net/Md_Ashfaqur_Rahman/m92qz82n/

if the above is not fix then see it
and also not working with javascript multiple class selector
https://jsfiddle.net/Md_Ashfaqur_Rahman/m92qz82n/2/

**Comment by himak** [comment]
I have same problem :/

**Comment by kimmobrunfeldt** [comment]
I'm sorry but I really don't understand what's the issue here. If you need two progressbars, you need to call `new ProgressBar.Circle(...` twice.
