### ISSUE TITLE
How to destroy an animation event? help pls

### ISSUE THREAD

**Issue by sumitkalia** [kimmobrunfeldt/progressbar.js#205]
function initialize_lineanimation(id_name,width1,color1){
var bar = new ProgressBar.Line(window[id_name], {
  strokeWidth: width1,
  easing: 'easeInOut',
  duration: 1400,
  color: color1,
  trailColor: '#f8f9fa',
  trailWidth: width1,
  svgStyle: {width: '100%', height: '100%'},
  text: {
    style: {
      // Text color.
      // Default: same as stroke color (options.color)
      color: '#999',
      position: 'absolute',
      right: '0',
      top: '10px',
      padding: 0,
      margin: 0,
      transform: null
    },
    autoStyleContainer: false
  },
  from: {color: color1},
  to: {color: '#ED6A5A'},
  step: (state, bar) => {
    bar.setText(Math.round(bar.value() * 100) + ' %');
  }
});
bar.animate(($("#"+id_name).attr("aria-valuenow")/100));  // Number from 0.0 to 1.0
}

I have this simple code and i am calling it as initialize_lineanimation("div_id",5,"#28a745");

Now I am calling this function again on the same page. How can i destroy previously opened animation. It's giving me second layer.

**Comment by MKaslan1** [comment]
Example.com

**Comment by kimmobrunfeldt** [comment]
There's a [.destroy()](http://progressbarjs.readthedocs.io/en/latest/api/shape/#destroy) method which can be used to destroy the previous one.
