### ISSUE TITLE
es6 import & typings

### ISSUE THREAD

**Issue by Gouigouix** [kimmobrunfeldt/progressbar.js#206]
Hello,

I tried to import into a TypeScript project the library using the notation es6, without result!
```
import * as ProgressBar from 'progressbar'; // <--- not working
// import ProgressBar from 'progressbar'; // <--- not work too, no export default

const circle = new ProgressBar.Circle ('# example-percent-container', {
     color: '#FCB03C',
     strokeWidth: 3,
     trailWidth: 1,
     text: {
         value: '0'
     }
});
````
but 
```
const ProgressBar = require ('progressbar.js'); // <--- works

const circle = new ProgressBar.Circle ('# example-percent-container', {
     color: '#FCB03C',
     strokeWidth: 3,
     trailWidth: 1,
     text: {
         value: '0'
     }
});
```

Then, I did not find a typing file for the library, someone has concocted one on his side?

Thank you.

**Comment by pklink** [comment]
```javascript
import ProgressBar from 'progressbar.js'
```

is working fine. Do you have forgotten the `.js` in your import clause?

**Comment by KayHS** [comment]
@pklink This does not work for me either. Imported exactly as you. it comes up with progressbar is not defined.

`Cannot read property 'Circle' of undefined`

**Comment by kimmobrunfeldt** [comment]
I believe this is a more common problem with TypeScript imports, and they have recently done some updates related to this so that you wouldn't need the `*` import anymore. Unfortunately I don't have plans to improve the TS support at the moment.

**Comment by hasmai** [comment]
I know it's closed issue but just thought because there is a space between '# example-percent-container'? Was that reason for not working?

**Comment by stgermaniac** [comment]
import * as ProgressBar from 'progressbar.js';    (seems to do the trick)
