### ISSUE TITLE
Countdown in minutes

### ISSUE THREAD

**Issue by r3dh0t** [kimmobrunfeldt/progressbar.js#208]
How can I make the value in the centre of the progress bar show as minutes, counting down?

i.e. 5 minutes to 0

**Comment by kimmobrunfeldt** [comment]
Unfortunately I don't have time to help with this. Hopefully you can find more from google.

**Comment by AlinChindea** [comment]
Use this library https://github.com/albert-gonzalez/easytimer.js - easy to use and will do the trick
