### ISSUE TITLE
How to bring Circle above the Stroke Path

### ISSUE THREAD

**Issue by vikkya** [kimmobrunfeldt/progressbar.js#212]
Hi, 

Im trying to get the circle to foreground i.e circle should be above the stroke path.

Here is the fiddle https://jsfiddle.net/3znuxaxs/343/

I want the black circle above the green path.

I tried style with z-index and position but it didn't work.

Need some help here

**Comment by zengodesign** [comment]
Hey there,

I added some css on the code, it is not perfect or complete but it might be a starting point:
I used your fiddle you provided (**I removed the fill element from your javascript file**)
Added CSS:
.progressbar__label{
    color: rgb(111, 213, 127);
   
  }
  #example-animation-container {
    width: 152px;
    height: 152px;
    border-radius: 76px;
    z-index: -99;
    position: relative;
  }
  #container_id {
    z-index: 999;
    background: magenta;
    width: 140px;
    height: 140px;
    border-radius: 70px;
    top: 58px;
    left: 6px;
    position: absolute;
    content:"";
  }
Changed the HTML like this and had some success ( you might want to experiment with it a bit):
<div id="example-animation-container">
<div id="container_id" >
<span id="animatePercentage"></span></div>
<p>Documentation: <a href="https://github.com/kimmobrunfeldt/progressbar.js/blob/master/README.md">ProgressBar.js</a></p>
</div>

**Comment by kimmobrunfeldt** [comment]
Unfortunately the fill is by default under the actual progress bar. You could achieve what you want with an another e.g. div which is on top of the progressbar SVG. Set the background as black, border-radius to 50% etc.

Hope this helps.
