### ISSUE TITLE
ES6 and Javascript class for ProgressBar

### ISSUE THREAD

**Issue by JohnnieMacarroni** [kimmobrunfeldt/progressbar.js#214]
Hi,

I want to create a class that will receive some values from other class that will include a loop to create 5 progress bars with values that will come from a .fetch REST controller.

I was trying to do something of the sort, as I am new to Javascript and ES6 annotations, and I haven't managed to make it work so far. 

Any help would be appreciated

This is my ProgressBar.class so far

`import React, { Component } from "react";
import axios from 'axios';
import "./Homepage.css";
import ProgressBar from "react-progressbar.js";

class TaskGraph extends Component{

    

    constructor(props){
        super(props);
        this.match;
        this.state = {
            progress: ''

        
        }
    }

    render(){

        var options = {
            strokeWidth: 2
        };

        var containerStyle = {
            width: '200px',
            height: '200px'
        };

        return(
            <div className="Graph">

            <circle />

            </div>
        )
    }

}

export default TaskGraph`

**Comment by kimmobrunfeldt** [comment]
This issue would belong to https://github.com/kimmobrunfeldt/react-progressbar.js.
