### ISSUE TITLE
Can I specify strokeWidth and trailWidth in pixels (px)?

### ISSUE THREAD

**Issue by BenJackGill** [kimmobrunfeldt/progressbar.js#223]
I need to set the width of my semiCircle progress bars in `px` so that it will match the width of other elements on the page.

The problem with using points (the default method of choosing the progressbar width) is that it is a percentage of the container, and not a set amount. This means progressbars in different containers will have different widths.

So is it possible to set the `strokeWidth` and `trailWidth` in `px` instead of points?

I have tried the following but the progressbar doesn't even show when using these:
```
strokeWidth: 10px,
trailWidth: 10px,
```
```
strokeWidth: '10px',
trailWidth: '10px',
```
Or perhaps someone has found a work around for this?

**Comment by bennygill** [comment]
Ignore this, I have just learned that pts = px when the canvas size is not scaled.

**Comment by tigerste** [comment]
There's an svg path CSS property that would ordinarily allow you to do this:
`vector-effect:non-scaling-stroke`
Whilst this stops the stroke scaling based on dimensions of the svg, it breaks the animation because `stroke-dasharray` is used to animate the path, rather than `pathLength` - @kimmobrunfeldt is this something that could be supported?

**Comment by kimmobrunfeldt** [comment]
Hi,

good question. SVGs are designed to be scalable, and units are always relative to the container. You can achieve this by controlling the container size. Let's say you have a circle progress bar inside a `100px` x `100px` container. In that scenario, `strokeWidth: 10`, means 10% of the container and should equal 10px.

@tigerste vector-effect is quite new feature of SVG, and not all browsers support it:
https://stackoverflow.com/questions/29792252/svg-vector-effect-non-scaling-stroke-and-ie
