### ISSUE TITLE
How to import Progressbar correctly?

### ISSUE THREAD

**Issue by legionio** [kimmobrunfeldt/progressbar.js#225]
Please see my question here: https://stackoverflow.com/questions/51219644/how-do-i-import-progressbar-js-in-laravel

I can't seem to require/or import progress js... any advice would be appreciated.

**Comment by legionio** [comment]
No one monitoring this anymore??

**Comment by cte4X** [comment]
`import Progressbar from "progressbar.js";`

**Comment by legionio** [comment]
Issue was with NPM.
