### ISSUE TITLE
Is it possible to reset the status of the progress bar to zero

### ISSUE THREAD

**Issue by grantkemp** [kimmobrunfeldt/progressbar.js#240]
Is it possible to reset/ restart the progress bar? Every time I do this it just seems to add another progress bar below it?

**Comment by grantkemp** [comment]
bar.animate solved this!

**Comment by sagive** [comment]
how to to this inside a function if i have multiple items 
say we click on a parent and we want its child to re-play / animate
meaning we don't have the "bar" variable.. how do we recreate it 
based on parent / click etc ?
