### ISSUE TITLE
Browser(IE) Related Issue

### ISSUE THREAD

**Issue by SachinThakur** [kimmobrunfeldt/progressbar.js#241]
Hi ,
This works perfectly on IE ( Version : 11 ) browser but when i increased strokeWidth,trailWidth parameter value more than 8 then its not work in IE browser while works in chrome and mozila.

Thanks,
Sachin

**Comment by kimmobrunfeldt** [comment]
Hi, this is indeed very strange bug. Duplicate of https://github.com/kimmobrunfeldt/progressbar.js/issues/79
