### ISSUE TITLE
Delay Parameter? 

### ISSUE THREAD

**Issue by OzzyD25** [kimmobrunfeldt/progressbar.js#249]
Not really an issue, but I was wondering if there was a delay parameter or something to delay the animation ? 

eg ....

  const bar2 = new ProgressBar.Path('#path', {
      easing: 'easeInOut',
      duration: 2200,
      delay: ? 
    });

    bar2.set(0);
    bar2.animate(1.0);

**Comment by over-engineer** [comment]
Hello @OzzyD25,

right now there isn't a delay parameter, but I'm going to open a PR to add it.

So, hopefully there will be once it gets reviewed and merged 😄

**Comment by kimmobrunfeldt** [comment]
What's your use case for the delay parameter? In all cases I can think of, it should be possible to use for example `setTimeout(() => bar2.animate(1.0), 1000)` to achieve a 1s second delay.

**Comment by kimmobrunfeldt** [comment]
The final implementation was so small change that I happily merged the change. Delay option is now available in the latest version.
