### ISSUE TITLE
Text label is off-center on Safari

### ISSUE THREAD

**Issue by mawax** [kimmobrunfeldt/progressbar.js#41]
The text label is off-center in Safari (tested on Safari 7.1.2 and OS X 10.9.5).

Also happens on the demo page:
![safari](https://cloud.githubusercontent.com/assets/10511783/5722391/1ae5be10-9b3c-11e4-9e3c-1b1ae4eaa9fa.png)

**Comment by kimmobrunfeldt** [comment]
Thanks for pointing it out. I'll look into it

**Comment by kimmobrunfeldt** [comment]
The fix for this was released in 0.7.3, but that release was quite a failure which broke stuff. You should update to 0.7.4.
