### ISSUE TITLE
How to set path count like circle and square ?

### ISSUE THREAD

**Issue by hamdan-mahran** [kimmobrunfeldt/progressbar.js#43]
Hi, Thanks for this awesome plugin :)
my path works good but i want it to count from (0%) to its value (70%)
<pre>
var container = document.getElementById('example-custom-container');
					container.innerHTML = '<object id="scene" type="image/svg+xml" data="images/heart.svg"></object><span class="path_val"></span><p class="progressbar-text"></p>';
					
					var scene = document.getElementById('scene');
					scene.addEventListener('load', function() {
						var path = new ProgressBar.Path(scene.contentDocument.querySelector('#heart-path'), {
							duration: 2000,
							easing: hm_animation, 
							step: function(state, circle) {
							      circle.setText((circle.value() * 100).toFixed(0) + " %");

							}
						});
					
						path.animate(1, function() {
							
						});
					});
</pre>

Thanks very much

**Comment by kimmobrunfeldt** [comment]
You are using the Path, which doesn't offer you setText method because your shape could be anything and there's no obvious position for the text.

If you want to have a text with custom Path, you should have your own e.g. <p> element and update it from the step function.

**Comment by kimmobrunfeldt** [comment]
I don't fully understand what you are trying to achieve. If you want more specific tips, put your working code to JSFiddle or similar service and link it here :)

**Comment by hamdan-mahran** [comment]
Hi @kimmobrunfeldt  :)
Thanks very much for your reply and your time.
i make my example in the following link, but its work on my local, and the first shape works good,
what i want is : your example use (id) with svg and container, but i want to use many shapes in the same page :(
http://jsfiddle.net/idealtheme/dn9e2b74/18/
Thanks any way for your kindness

**Comment by kimmobrunfeldt** [comment]
Using containers with different ids for separate progress bars is possible
