### ISSUE TITLE
The instance of the ProgressBar Shape/Path should be accessible from the step function.

### ISSUE THREAD

**Issue by prodigitalson** [kimmobrunfeldt/progressbar.js#48]
Unless i missed something, when using `ProgressBar.Path` there is no way to get the reference to itself from the `step` function supplied in instantiation unless using some round about referencing method. I would propose this also be passed as an argument to `step` or merged in to the `state` provided to step. 

Example usage would be to animate a progress bar on an irregular shaped custom path (like an arc) and also animate some text like a counter (similar to what is built in to circle and line) and might be achieved with the following:

    var svgPath = document.getElementById('svgPath'),
          counter = document.getElementById('counter');

    var p = new ProgressBar.Path(svgPath, {
          duration: 800,
          from: { strokeOffset: svgPath.getTotalLength() },
          to: { strokeOffset: 0 },
          attachment: { path: svgPath, counter: counter },
          // here self would be a ref to the ProgressBar.Path instance
          step: function (state, attachment, self) {
              attachment.path.setAttribute('strokeOffset', state.strokeOffset);
              attachment.counter.innerHTML = (self.value()*100);
          }
    });

    p.animate(0.75);

**Comment by kimmobrunfeldt** [comment]
That's a good point. I remembered that self was passed as attachment but nope. At first glance, it seems that passinh the path always as third parameter would be good solution

**Comment by prodigitalson** [comment]
If I have time later I'll try and update the docs, but as it stands I spent a bit to much time on this... Thanks for the crash course in Mocha and Sinon though ;-)

**Comment by prodigitalson** [comment]
So i was just updating the docs, and I wonder, should we update the `Shape` derived progress bars to pass an empty/merged object as `attachment` and then let them pass `this` as the third argument so that the API is consistent or are we ok with just allowing `Path` do this since its a special case?

**Comment by kimmobrunfeldt** [comment]
Good question. I think the best would be to pass reference to `Shape` or `Path` as a separate parameter and leave attachments only for the library user. I have implemented it so that by default, reference to `Shape` is passed as the `attachment`. If user overrides the `attachment`, they can't get reference to the `Shape` inside `step` function. That's not good. I think the `attachment` should be left for only library users. That way the internal reference passing wouldn't be messed up if user wants to customize the `attachment`.

I propose:

```javascript
function step(state, self, attachment) { ... }
```

`self` is reference to `Path` or `Shape` derived progress bar depending which was initialized. This changes the API a bit, but the parameter order makes sense in the way that `state` and `self` always contain a value, attachment might be *undefined*.

**Comment by kimmobrunfeldt** [comment]
What do you think?

**Comment by prodigitalson** [comment]
@kimmobrunfeldt That sounds much more intuitive/proper to me. I'll go ahead and get started on those changes and doc updates. Should I also do the MAJOR version bump or will you handle that?

**Comment by kimmobrunfeldt** [comment]
Ok sounds good. I'll handle the version bumps and release specific stuff. Since we are below 1.0.0 version, I'll do a minor bump.

**Comment by prodigitalson** [comment]
@kimmobrunfeldt Ok updates pushed. See my note on the PR and commit for some additional changes I made to the test setup.

**Comment by kimmobrunfeldt** [comment]
I was about to release new version with this included. But I found out a couple of issues. I'll fix them and make the release.

**Comment by kimmobrunfeldt** [comment]
This is now released as 0.8.0 https://github.com/kimmobrunfeldt/progressbar.js/releases/tag/0.8.0

**Comment by prodigitalson** [comment]
Great, i've been waiting for this release so I can update my project with the official dist. Thanks @kimmobrunfeldt
