### ISSUE TITLE
Path not working

### ISSUE THREAD

**Issue by ZachSaucier** [kimmobrunfeldt/progressbar.js#54]
I am trying to create a custom path animation and it doesn't seem to be animating for me. I tried the demo (heart) code here http://jsfiddle.net/xrbfw21o/1/ yet that doesn't seem to work either.

Any idea what's going on?

**Comment by ZachSaucier** [comment]
Well, I'm stupid. Didn't call the animate function... http://jsfiddle.net/xrbfw21o/2/

**Comment by ZachSaucier** [comment]
On a side, note, is there a way to use a custom SVG path for a bunch of elements without copying the SVG originally? As in initialize it once in the HTML but have ProgressBar copy it for as many elements as I need it on?

**Comment by kimmobrunfeldt** [comment]
progressbar.js doesn't provide the copy functionality you would need, you have to figure a way to copy the SVG element outside this library.
