### ISSUE TITLE
Stacked

### ISSUE THREAD

**Issue by ziazek** [kimmobrunfeldt/progressbar.js#56]
Any way to make stacked progress bars within the circle?

**Comment by kimmobrunfeldt** [comment]
This issue is about progressbars in columns, not stacked but you get the idea https://github.com/kimmobrunfeldt/progressbar.js/issues/53

**Comment by kimmobrunfeldt** [comment]
Or do you mean like this? http://jsfiddle.net/55y95n50/

**Comment by ziazek** [comment]
Hi kimmobrunfeldt, 

Yes, I meant the latter one.

**Comment by kimmobrunfeldt** [comment]
Ok great. Somehow the paths behind leak and it doesn't look very smooth. I don't know why it happens.
