### ISSUE TITLE
How can I limit it to a specific percentage?

### ISSUE THREAD

**Issue by edwardoyarzun** [kimmobrunfeldt/progressbar.js#59]
I'm using this library to represent the percentage of CPU and RAM of a computer.
How can I set a specific percentage, e.g. 40%.

**Comment by edwardoyarzun** [comment]
Nevermind, I did it

**Comment by kimmobrunfeldt** [comment]
I updated examples in homepage and JSFiddle to communicate it more clearly. For others finding this issue, here's an example: http://jsfiddle.net/tnmupvqf/

```javascript
var circle = new ProgressBar.Circle('#container', {
    color: '#FCB03C',
    trailColor: '#eee'
});

var percent = 40;
circle.animate(percent / 100);  // Number from 0.0 to 1.0
```
