### ISSUE TITLE
Is it possible to generate semi-circles?

### ISSUE THREAD

**Issue by edwardoyarzun** [kimmobrunfeldt/progressbar.js#61]

**Comment by kimmobrunfeldt** [comment]
There isn't.. yet! But I've been thinking of this and I could whip off support for that. I'm not sure if anyone uses the Square shape, so I could remove it from the release and offer it as a plugin / something instead.

**Comment by kimmobrunfeldt** [comment]
I added semicircle. It's now on master. I introduced a few new options to help adjusting the text for semi circle. See an example http://codepen.io/anon/pen/waaMwM

**Comment by kimmobrunfeldt** [comment]
I'll release it after testing and thinking of the API a few days

**Comment by edwardoyarzun** [comment]
Ok, thanks.

**Comment by kimmobrunfeldt** [comment]
This has been hanging around for quite long.. I'm not satisfied with the text implementation after introducing semi-circle.

**Comment by kimmobrunfeldt** [comment]
Support for this is now released in progressbar.js@0.9.0.
