### ISSUE TITLE
Circular progress bar around an image

### ISSUE THREAD

**Issue by IngwiePhoenix** [kimmobrunfeldt/progressbar.js#64]
I am working on a user module for my site and I would like to use a progress bar around a circle, in which the image will be displayed once uploaded, so it takes up less space on the page itself.

How would I go about drawing the circle around the image? I am using Bootstrap as a CSS framework and it has a circular thumbnail class, which I am using to make the image into a circle.

**Comment by kimmobrunfeldt** [comment]
Here are few examples of how to achieve this with CSS:
*

**Comment by IngwiePhoenix** [comment]
Sweet! :) The second is exactly what I was looking for. Thank you for the jsfiddle, I am going to sit down and implement it now. :)
