### ISSUE TITLE
Gradient pattern to 1 instead of value

### ISSUE THREAD

**Issue by alexcroox** [kimmobrunfeldt/progressbar.js#66]
Following the example where the progress path goes from red to green on completion, I'd like a gradient that's red at 0 and green at 1. Meaning if the bar stops at 50%, it won't be green. In the example code the circle ends up as green even if the value is only 0.5.

**Comment by kimmobrunfeldt** [comment]
Here's more how to customize animations: https://github.com/kimmobrunfeldt/progressbar.js/blob/master/README.md#custom-animations

You probably mean the "passing in initialization"

**Comment by alexcroox** [comment]
Ah perfect thank you very much!
