### ISSUE TITLE
Size incorrect in IE

### ISSUE THREAD

**Issue by ts-Mike** [kimmobrunfeldt/progressbar.js#67]
It seems the height/width are around half the size they should be when viewing a circular progress bar in IE. This applies not only to my project, but also your project website's examples. Open your site in IE11 to see what I mean.

**Comment by kimmobrunfeldt** [comment]
Hmm strange, I'll look into this at some point. Probably a CSS problem where svg does not resize to its container

**Comment by Astyan42** [comment]
What's the status of this issue ?

**Comment by wwymak** [comment]
Also, in IE 9/10 if you use a progress line setting the stroke-width option doesn't seem to affect how thick the line is, rather the container controls it -- as my container for the progress bar has extra padding to go with the rest of the document, it means the progress bar is really thick in IE... (not an issue in Chrome or Firefox) 
I have to set the width and height of the svg element for the progress bar in the css to get it to work-- would be nice if this can be fixed

**Comment by kimmobrunfeldt** [comment]
@wwymak that is intentional behavior. You should set the height of the container to control the width of Line bar.

**Comment by kimmobrunfeldt** [comment]
This should be automatically fixed in new release: progressbar.js@0.9.0.

Demo page is not updated to new version yet as I'm redesigning it.

**Comment by kimmobrunfeldt** [comment]
The demo page still not working

**Comment by pink-bunny** [comment]
Where I can find update version progressbar.js@0.9.0 ?

**Comment by kimmobrunfeldt** [comment]
This issue is not happening with the new demo page. 

@pink-bunny newest unminified code is here: https://github.com/kimmobrunfeldt/progressbar.js/blob/master/dist/progressbar.js or in NPM.
