### ISSUE TITLE
How can I access a ProgressBar object instance from outside the context?

### ISSUE THREAD

**Issue by edwardoyarzun** [kimmobrunfeldt/progressbar.js#68]
For example if I do:

    var circle = new ProgressBar.Circle('#example-animation2-container', { my options... });

But that instance is made on another context so I can't access the 'circle' object.
Is there a way to access the object from Jquery?, something like this:

    $("#example-animation2-container").progressbar()

**Comment by kimmobrunfeldt** [comment]
There isn't such way to access the progressbar afterwards. You need to store the circle reference to somewhere where you can access it.
