### ISSUE TITLE
how to Redraw the circle progress bar on the same object 

### ISSUE THREAD

**Issue by mahdi87gh** [kimmobrunfeldt/progressbar.js#69]
Hi
I want to redraw the circle progress bar on the same object on mouse hover. but when i draw a new progress bar, after 2 or 3 times, edges get pixelated.
here is my code

<div class="content">
        <div class="progress" id="progress" data-color="#29A329" data-from="#80E680" data-to="#005200">
            <div class="c-content">
                this is a test1
            </div>
        </div>
        <div class="progress" id="progress2" data-color="#fff" data-from="#bbb" data-to="#000">
            <div class="c-content">
                this is a test2
            </div>
        </div>
        <div class="progress" id="progress3" data-color="#fff" data-from="#bbb" data-to="#000">
            <div class="c-content">
                this is a test3
            </div>
        </div>
    </div>

$('.progress').hover(function () {
            var circle = new ProgressBar.Circle(this, {
                strokeWidth: 2,
                from: { color: $(this).attr('data-from') },
                to: { color: $(this).attr('data-to') },
                duration: 1000,
                easing: 'easeInOut',
                step: function (state, circle, attachment) {
                    circle.path.setAttribute('stroke', state.color);
                }
            });

            circle.animate(1);
        },
        function () {
            var circle = new ProgressBar.Circle(this, {
                strokeWidth: 2,
                color: $(this).attr('data-color'),
                duration: 1000,
                easing: 'easeInOut'
            });

            circle.animate(1);
        }
        );

        window.onload = function onLoad() {
            $('.progress').each(function (idx, p) {
                console.log($(p).attr('id'));
                var circle = new ProgressBar.Circle(p, {
                    strokeWidth: 2,
                    color: $(p).attr('data-color'),
                    //from: { color: $(p).attr('data-from') },
                    //to: { color: $(p).attr('data-to') },
                    duration: 2000,
                    easing: 'easeInOut'
                });

                circle.animate(1);
            });
        };

**Comment by kimmobrunfeldt** [comment]
It seems that you have this issue https://github.com/kimmobrunfeldt/progressbar.js/issues/65

**Comment by mahdi87gh** [comment]
I think my problem is not the same #65 
is there a way to destroy the previous object and create another one?
tahnks

**Comment by kimmobrunfeldt** [comment]
You can use [.destroy()](https://github.com/kimmobrunfeldt/progressbar.js#shapedestroy) method to destroy any instance. If you want to re-animate using the same instance, you could do:

```javascript
bar.set(0);
bar.animate(1);
```

**Comment by mahdi87gh** [comment]
Thanks
I'll give it a try. Is is possible to change the colors during re-animate?
I want to re-animate with new colors on hover.

**Comment by kimmobrunfeldt** [comment]
You can access the underlying SVG paths with: `bar.path` and `bar.trail`.

To set the color of the bar:

```javascript
bar.path.setStyle('stroke', 'red');
```

**Comment by mahdi87gh** [comment]
Thanks
It works
