### ISSUE TITLE
Rounded corners on circle

### ISSUE THREAD

**Issue by sean-hill** [kimmobrunfeldt/progressbar.js#71]
Is there a way to round the corners on the circle? For instance something like [this](http://ignitersworld.com/lab/radialIndicator.html). Thanks!

**Comment by sean-hill** [comment]
I added this line to the library:

    this.path.style.strokeLinecap = 'round';

And it workes, but it'd be nice to have that as an option :smile:

**Comment by kimmobrunfeldt** [comment]
This is something I implemented but removed since it was hard to implement for e.g line. The rounding cap goes out of the canvas with Line. Do you have ideas how to overcome that issue?

**Comment by sean-hill** [comment]
I don't sorry, canvas ain't my thing :smile:

**Comment by kimmobrunfeldt** [comment]
The implementation is using just SVG, and was talking about SVG's canvas. I'm open for ideas from anyone.

**Comment by kimmobrunfeldt** [comment]
Closing this for now. You can achieve this by setting the style manually as mentioned above:

```javascript
var bar = new ProgressBar.Circle('#container');
bar.path.style.strokeLinecap = 'round';
```

**Comment by Abdullaicf** [comment]
Is there a way to increase the radius of strokeLinecap
