### ISSUE TITLE
Issue with the stroke showing in rgb not HEX

### ISSUE THREAD

**Issue by phara0hcom** [kimmobrunfeldt/progressbar.js#75]
I have an issue that the stroke in showing in RGB not HEX so it doesn't show in IE
![untitled-1](https://cloud.githubusercontent.com/assets/4345712/7882816/af06061e-0611-11e5-8964-1e83ee345136.png)
How do I get it in HEX?
all the variables are in HEX

my code:

	var element = document.getElementById('timeC');
	var circle = new ProgressBar.Circle(element, {
		trailColor: '#D8D8D8',
		trailWidth: 10,
		strokeWidth: 10,

		// Set default step function for all animate calls
		step: function(state, circle) {
			circle.path.setAttribute('stroke', state.color);
		}
	});

to start the circle:

	circle.set(0);
	circle.animate(0.5, {
		from: {color: '#00FF00'},
		to: {color: '#FFAE00'},
		duration: 7500
	}, function(){
		circle.animate(0.99, {
			from: {color: '#FFAE00'},
			to: {color: '#FF0004'},
			duration: 10000
		});
	});

**Comment by kimmobrunfeldt** [comment]
The conversion from hex to rgb color is done by shifty, tweening library: https://github.com/jeremyckahn/shifty

Are you sure it is IE problem? Which version?

**Comment by phara0hcom** [comment]
IE 11 on win7

**Comment by phara0hcom** [comment]
but how do I stop it from converting?

**Comment by kimmobrunfeldt** [comment]
I don't think that is your real problem. IE should support rgb color definition just as it supports hex. I just tested this with a jsfiddle using IE and it draws the SVG correctly. http://jsfiddle.net/b6fp1sy7/

**Comment by kimmobrunfeldt** [comment]
That is probably related to CSS layouting. Try to:

```css
#container > svg {
  display: block;
  width: 100%;
}

```

**Comment by phara0hcom** [comment]
I can see it because I can see the trail that is colored in HEX but not the stroke...

**Comment by kimmobrunfeldt** [comment]
I could not confirm this behavior.
