### ISSUE TITLE
How to use this outside of windows.onload()?

### ISSUE THREAD

**Issue by Karmaschinken** [kimmobrunfeldt/progressbar.js#76]
Hello, I am sure this is a stupid beginners question, that´s because I am such. 

I want to make a circle animate outside "windows.onload" but instead in a function. Could anybody help me with that?

This is what I tried:

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>ProgressBar.js - Minimal Example</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <style>
            .progress {
                height: 50px;
            }

            .progress > svg {
                height: 100%;
                display: block;
            }
        </style>
        <script type="text/javascript">
			function MyFunction()
			{	
				circle = document.getElementById("progress");
				if(circle)
					alert(circle);
				circle.set(0.8);
			}
		</script>

    </head>
    <body>
        <div class="progress" id="progress"></div>

        
        <script src="progressbar.js"></script>

        
        <script>
        window.onload = function onLoad() 
		{
			var circle = new ProgressBar.Circle('#progress', 
				{
					color: '#009cff',
					duration: 1000,
					strokeWidth: 10,
					trailWidth: 10,
				}
			);
		};
		</script>
        
		<a id="myLink" href="#" onclick="MyFunction();">link text</a     
    ></body>
</html>

**Comment by kimmobrunfeldt** [comment]
I really recommend reading some basic JS tutorials. As you said, there's a pretty basic scoping problem in your code and a few errors. 

* `document.getElementById` returns a DOM element, not a ProgressBar.Shape instance. You can't call ProgressBar methods to a DOM element.
* You have `progress` selector, which won't work. You probably mean `#progress` or something like that.
* `onclick="MyFunction();"` is not recommended
* Naming issues, e.g. function named `MyFunction` should be `myFunction`


One way (not a good one) to get your code working is to:
```javascript
window.onload = function onLoad() 
    {
        circle = new ProgressBar.Circle('#progress', 
            {
                color: '#009cff',
                duration: 1000,
                strokeWidth: 10,
                trailWidth: 10,
            }
        );
    };
```

```html
<a id="myLink" href="#" onclick="circle.set(0.8);">link text</a     
```

That code is still pretty bad, and contains a lot of confusing and bad practices, e.g. having circle as global variable.
