### ISSUE TITLE
Starting point in svg

### ISSUE THREAD

**Issue by Squidy06** [kimmobrunfeldt/progressbar.js#80]
Hi, 
I don't really understand how to set starting point of the animation, even with your "Heart" example.
http://jsfiddle.net/8xa87k31/513/
How can I start the animation from top center point?

**Comment by kimmobrunfeldt** [comment]
The SVG needs to be constructed so that that starting point of the path is at a specific point.

**Comment by kimmobrunfeldt** [comment]
More specificly, the starting point can't be set with progressbar.js. You need to draw the SVG path so that it starts from the point where you want. In this case you need to modify the heart.svg to achieve that.
