### ISSUE TITLE
Having issues in IE 11

### ISSUE THREAD

**Issue by aquamoose** [kimmobrunfeldt/progressbar.js#81]
The progress bar doesn't show up in IE 11.
It gave me this error
bg.getContext('2d').drawImage(img, 0, 0, size, size);
Can you please look into it?

**Comment by kimmobrunfeldt** [comment]
Please provide more details of the issue. That is not an error, it's is a line of code. More precisely, some code which is not from this library's source code.

**Comment by kimmobrunfeldt** [comment]
I'll close this due inactivity and lack of information about the issue.
