### ISSUE TITLE
Suggestion: add discrete step progress bars with text.

### ISSUE THREAD

**Issue by AlexFrazer** [kimmobrunfeldt/progressbar.js#89]
For example, a progress bar that might look like:

```
|---------------------|------------|----------------------------|-------------------|
|      creating       | starting   |        generating          |     installing    |
|---------------------|------------|----------------------------|-------------------|
```

Where each discrete step is a certain percent of the bar

**Comment by kimmobrunfeldt** [comment]
You can achieve this with the step function, see this example: http://jsfiddle.net/vuyjthqn/2/

Code for reference:

**JS**
```js
// Not the prettiest way to return progress as text
function getStep(progress) {
    if (progress > 0.999999) {
        return 'done';
    } else if (progress > 0.75) {
        return 'installing';
    } else if (progress > 0.5) {
        return 'generating';
    } else if (progress > 0.2) {
        return 'starting';
    } 
    
    return 'creating';
}

var bar = new ProgressBar.Line('#container', {
    color: '#FCB03C',
    trailColor: '#eee',
    // Take the full height of the SVG canvas(100%)
    strokeWidth: 100,
    from: {
        textColor: '#FCB03C'
    },
    to: {
        textColor: '#ffffff'
    },
    step: function(state, bar) {
        bar.setText(getStep(bar.value()));
        bar.text.style.color = state.textColor;
    },
    duration: 5000
});

bar.animate(1.0);  // Number from 0.0 to 1.0
```

**CSS**
```css
#container {
    width: 500px;
}

#container > svg {
    width: 500px;
    height: 25px;
}

#container > p {
    font-weight: bold;
}
```

**HTML**
```html
<div id="container"></div>
```

**Comment by kimmobrunfeldt** [comment]
Did the above example help or would you like the bar to visually have this kind of overlay? If yes, I don't consider it to be very common usage and wouldn't like to add it to the core API. This kind of visual style could be done via a new Shape. Something like LabelLine(*just a random thought of a name*). You can do it by copying how line.js works.

I consider this closed for now. This can be achieved with a new shape but I don't think I'll implement this behavior directly to the library. I need to consider a plugin architecture if this is a more common use case. So others wanting the same, please reopen / comment this issue.
