### ISSUE TITLE
Add support for stroke-linecap

### ISSUE THREAD

**Issue by kimmobrunfeldt** [kimmobrunfeldt/progressbar.js#9]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap

Currently in line path, the rounding goes out of the SVG canvas.

**Comment by andreiglingeanu** [comment]
Hey @kimmobrunfeldt, is there any way to avoid overflows for `Line` when attaching `stroke-linecap` as `round`?

**Comment by kimmobrunfeldt** [comment]
@andreiglingeanu I haven't been able to fully solve that yet unfortunately. With a custom SVG you could solve this for sure.
