### ISSUE TITLE
How can I change certain progress (e.g Line) to reverse mode.

### ISSUE THREAD

**Issue by jimzhan** [kimmobrunfeldt/progressbar.js#92]
currently we have progress line running perfectly under incremental mode, how can we change it to reverse mode from 100% to 0% instead?

**Comment by kimmobrunfeldt** [comment]
Did you get this issue resolved?

To answer others, when the progress bar is at 100%, you can simply animate it to 0% by calling:

```js
var progressBar = new ProgressBar.Line('#container');
progressBar.animate(1);
```

**Comment by JapSeyz** [comment]
Can you start it off at a 100% and count down? I can't get it to behave when I try that.

You can follow my attempt here:
https://jsfiddle.net/swc64gg3/1519/

**Comment by dp85** [comment]
@JapSeyz In case you or anyone else still needs to have the progress bar go backwards/reverse, I was able to accomplish this by the following:

`var progressBar = new ProgressBar.Line('#container');
progressBar.set(1);
progressBar.animate(0);`
