### ISSUE TITLE
Seek to a specific point

### ISSUE THREAD

**Issue by RonCan** [kimmobrunfeldt/progressbar.js#94]
Hey, that's a wonderful library. I was wondering if there's a seek to a specific point in the progress bar function? Or you could guide me and I could write one if there isn't?

**Comment by kimmobrunfeldt** [comment]
Do you mean .set() method? https://github.com/kimmobrunfeldt/progressbar.js#shapesetprogress

**Comment by RonCan** [comment]
No, set method requires a specific progress value. Can the user click on a certain point in the circular progress bar and seek to that point? Think of the progress bar in  terms of a music player, round progress bar showing the current progress of the track and the user can seek to specific point

**Comment by kimmobrunfeldt** [comment]
Ok now I got what you mean. There's no support for that in the API, you have to figure out it outside this library. That should be a separate module which maps to user clicks on the container to certain progress. 

There are these nice additional features popping every now and then in issues. I haven't yet thought about how plugins could be added to the progressbar.js. I would definitely like to provide that "seek" feature as a plugin but not in the core. 

I'll leave this open if I get excited to start doing some work for the plugins.

**Comment by kimmobrunfeldt** [comment]
Here's a very quick example how to do that in practice:
http://jsfiddle.net/zt60tz98/1/

**JS:**
```js
var line = new ProgressBar.Line('#container', {
    color: '#FCB03C',
    trailColor: '#eee'
});

line.animate(.1);  // Number from 0.0 to 1.0

var container = document.querySelector('#container');
var maxWidth = container.offsetWidth;

container.addEventListener('click', function(event) {
    var containerX = event.pageX - this.offsetLeft;
	// var containerY = event.pageY - this.offsetTop

    var progress = containerX / maxWidth;
    console.log(progress)
    line.set(progress);
});
```

**Comment by RonCan** [comment]
I'm sorry I forgot to mention I was talking about the round progress bar. http://stackoverflow.com/questions/32668791/svg-path-get-relative-click-position This SO question is about another library but the point is the same, achieving the functionality with JS/Jquery.

**Comment by kimmobrunfeldt** [comment]
Then you have to calculate the rotation between container center and click position. That's something you need to do yourself. I might add this functionality later though, but can't promise anything.

**Comment by ethanclevenger91** [comment]
You might check out knob.js for this sort of task as well.

**Comment by kimmobrunfeldt** [comment]
Closing this issue. I'm not interested of implementing this to the core library but would see it as a possible plugin.
