### ISSUE TITLE
step attributes

### ISSUE THREAD

**Issue by danielone** [kimmobrunfeldt/progressbar.js#97]
From example:  

step: function(state, circle) {
        circle.path.setAttribute('stroke', state.color);
        circle.path.setAttribute('stroke-width', state.width);
  } });

is there an attribute trail-width to change the width of the trail? 
e.g,      circle.path.setAttribute('trail-width', state.width);

did not see a list of attributes that can set here as naming is different from params? Appreciate guidance here

**Comment by kimmobrunfeldt** [comment]
There is a `circle.trail` attribute which is also an SVG path. You can: `circle.trail.setAttribute('stroke', state.color);`

Note that if trail is not defined, `circle.trail` equals to null.

You can see all attributes and methods in the API documentation: https://github.com/kimmobrunfeldt/progressbar.js#api

**Comment by danielone** [comment]
Thank you @kimmobrunfeldt !!
