### ISSUE TITLE
Unable to center progress path

### ISSUE THREAD

**Issue by mmclau14** [kimmobrunfeldt/progressbar.js#99]
hi all, i'm not able to center the path on the trail here is the code that i'm using to generate my progress circle: 
```javascript
                view.progress = new ProgressBar.Circle(view.ui.progressCircle.get(0), {
                    color: app.utils.color(this.model.get('pieColor')),
                    strokeWidth: 9,
                    trailWidth: 9,
                    fill: app.utils.color('slate'),
                    trailColor: app.utils.color('slate-light'),
                    step: function (state, bar) {
                        bar.setText((bar.value() * 100).toFixed(0) + '%');
                    }
                });
```
and here's the result:
<img width="156" alt="screen shot 2015-11-21 at 5 41 31 pm" src="https://cloud.githubusercontent.com/assets/4896982/11321094/460ea288-9077-11e5-8409-be9336aee980.png">
as you can see, it's pretty close, but i need to get to a complete overlap of the trail and path like this:
<img width="164" alt="screen shot 2015-11-21 at 5 43 24 pm" src="https://cloud.githubusercontent.com/assets/4896982/11321097/63df0b0e-9077-11e5-8f48-fc5e13582eed.png">

**Comment by kimmobrunfeldt** [comment]
Could you replicate the issue in JSFiddle, you can fork this one: http://jsfiddle.net/kimmobrunfeldt/8xa87k31/392/

**Comment by mmclau14** [comment]
ok, so i got it almost there, by taking out the fill color. but now i'm left with a gaping hole where a slightly lighter shade of grey should be. is there a background property that i can use?

**Comment by mmclau14** [comment]
think i found a workaround, in my step function I put these two lines: 
```javascript
                        bar.trail.setAttribute('fill-opacity', '1');
                        bar.trail.setAttribute('fill', app.utils.color('slate'));
```

**Comment by kimmobrunfeldt** [comment]
Ok good that you got it working. I think you could achieve better performance by taking those calls out of the step function:

```js
var bar = new ProgressBar.circle('#container', /* opts .. */);
bar.trail.setAttribute('fill-opacity', '1');
bar.trail.setAttribute('fill', app.utils.color('slate'));
```
